### ISSUE TITLE
Dashboard not loading with DockerDesktop - error in chrome console - UserManager.getUser: user not found in storage No client_id passed 

### ISSUE THREAD

**Issue by lopatamd** [Arcan-Tech/arcan-issues-public#3]
**Describe the bug**
Started the app with Docker Desktop v20.10.13,  localhost:3000 loads partially the app (loads some js files but not showing anything, screenshot below)

**To Reproduce**
1 - docker-compose up
2 - go to localhost:3000

**Expected behavior**
Dashboard loading

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 21H2 x64 
 - Browser Chrome/Edge
 - Version - arcan trial

**Screenshots**

![image](https://github.com/Arcan-Tech/arcan-issues-public/assets/677908/2036b02a-cb3d-4302-b1c3-bc95ba6e5557)

![image](https://github.com/Arcan-Tech/arcan-issues-public/assets/677908/227b4a63-29d3-4112-9378-fe44c1d668d2)
![image](https://github.com/Arcan-Tech/arcan-issues-public/assets/677908/9de62578-8bb8-4526-8d9f-b2ceb6c61fe6)

**Comment by lopatamd** [comment]
forgot to add - no errors in docker logs in all containers

**Comment by darius-sas** [comment]
Hi @lopatamd . It seems like an authz related problem. Currently I'm ooo so I can't check the bug on my machine, but I'll have a look at it next week.

**Comment by darius-sas** [comment]
Haven't been able to reproduce on my machine even after a clean docker pull. I tried on both Firefox and Chrome and I can't get the error.

Could you please try with "InPrivate mode" or with Firefox and tell me if the problem persists? Also, could you also check that the clock on your machine is synced? 
If everything fails, you can always use [dashboard.arcan.tech/](https://dashboard.arcan.tech/).

**Comment by lopatamd** [comment]
ook basically after updating DockerDesktop it worked.
strange tho that i had the >v20.10 version which should have worked 
closing the issue now,
 i will try to see if the trial licence is still working
